name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - name: Install Node.js
      uses: actions/setup-node@v1.1.0
      with:
        # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0, lts
        version: 12.x
    - uses: actions/checkout@v1
    - uses: bahmutov/npm-install@v1

    - name: Generate cache key
      run: chmod +x ./android/checksum.sh && ./android/checksum.sh checksum.txt

    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches/jars-3
        key: ${{ runner.os }}-gradlejars-${{ hashFiles('checksum.txt') }}
        restore-keys: |
          ${{ runner.os }}-gradlejars-

    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches/build-cache-1
        key: ${{ runner.os }}-gradlebuildcache-${{ hashFiles('checksum.txt') }}
        restore-keys: |
          ${{ runner.os }}-gradlebuildcache-

    - name: Copy CI gradle.properties
      run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

    - name: Download gradle dependencies
      run: ./gradlew dependencies

    - name: Validate codestyle with Spotless
      run: ./gradlew spotlessCheck

    - name: Run static analysis
      run: ./gradlew detekt

    - name: Build app
      run: ./gradlew :app:assembleDebug
      
    - uses: actions/upload-artifact@v1
      with:
        name: debug apk
        path: android/app/build/outputs/apk/debug/app-armeabi-v7a-debug.apk
